package com.listocalixto.android.rembrandt.common.entities

import com.listocalixto.android.rembrandt.common.entities.composite.ArtworkUser
import com.listocalixto.android.rembrandt.common.entities.model.Color
import com.listocalixto.android.rembrandt.common.entities.model.Thumbnail

data class Artwork(
    val artistDisplay: String,
    val artistId: Int?,
    val artistTitle: String?,
    val artworkTypeId: Int,
    val artworkTypeTitle: String,
    val categoryIds: List<String>,
    val categoryTitles: List<String>,
    val color: Color?,
    val creditLine: String,
    val dateDisplay: String?,
    val dateEnd: Int?,
    val dateStart: Int?,
    val dimensions: String?,
    val galleryId: Int?,
    val galleryTitle: String?,
    val hasNotBeenViewedMuch: Boolean,
    val id: Long,
    val imageId: String,
    val imageUrl: String,
    val latitude: Double?,
    val longitude: Double?,
    val mediumDisplay: String?,
    val placeOfOrigin: String?,
    val score: Double,
    val termTitles: List<String>,
    val thumbnail: Thumbnail,
    val title: String,
) {
    constructor(artworkUser: ArtworkUser) : this(
        artistDisplay = artworkUser.artistDisplay,
        artistId = artworkUser.artistId,
        artistTitle = artworkUser.artistTitle,
        artworkTypeId = artworkUser.artworkTypeId,
        artworkTypeTitle = artworkUser.artworkTypeTitle,
        categoryIds = artworkUser.categoryIds,
        categoryTitles = artworkUser.categoryTitles,
        color = artworkUser.color,
        creditLine = artworkUser.creditLine,
        dateDisplay = artworkUser.dateDisplay,
        dateEnd = artworkUser.dateEnd,
        dateStart = artworkUser.dateStart,
        dimensions = artworkUser.dimensions,
        galleryId = artworkUser.galleryId,
        galleryTitle = artworkUser.galleryTitle,
        hasNotBeenViewedMuch = artworkUser.hasNotBeenViewedMuch,
        id = artworkUser.id,
        imageId = artworkUser.imageId,
        imageUrl = artworkUser.imageUrl,
        latitude = artworkUser.latitude,
        longitude = artworkUser.longitude,
        mediumDisplay = artworkUser.mediumDisplay,
        placeOfOrigin = artworkUser.placeOfOrigin,
        score = artworkUser.score,
        termTitles = artworkUser.termTitles,
        thumbnail = artworkUser.thumbnail,
        title = artworkUser.title,
    )
}
